### ISSUE TITLE
Error while fetching ratings for quote

### ISSUE THREAD

**Issue by doerfli** [etherisc/flightdelay-ui#89]
```
2024-10-10T15:20:32.925201763Z app[web.1]: {"level":"debug","message":"[fTW3Ay9qPILaf7vRQMxHw] fetching quote for BA 2231","timestamp":"2024-10-10 15:20:32"}
2024-10-10T15:20:32.925423325Z app[web.1]: {"level":"debug","message":"proxy request ==> GET https://api.flightstats.com/flex/ratings/rest/v1/json/flight/BA/2231?appId=96875f77&appKey=dc097f38175fd39620c72b94fc79be05","reqId":"fTW3Ay9qPILaf7vRQMxHw","timestamp":"2024-10-10 15:20:32"}
2024-10-10T15:20:33.024279303Z app[web.1]: {"level":"debug","message":"proxy response <== 200","proxyRequestDuration":98,"reqId":"fTW3Ay9qPILaf7vRQMxHw","timestamp":"2024-10-10 15:20:33"}
2024-10-10T15:20:33.025270332Z app[web.1]:  ⨯ TypeError: Cannot read properties of undefined (reading 'ontime')
2024-10-10T15:20:33.025282595Z app[web.1]:     at x (/app/.next/server/app/api/quote/[carrier]/[flightNumber]/route.js:1:2262)
2024-10-10T15:20:33.025286713Z app[web.1]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-10-10T15:20:33.025289728Z app[web.1]:     at async g (/app/.next/server/app/api/quote/[carrier]/[flightNumber]/route.js:1:1251)
2024-10-10T15:20:33.025292253Z app[web.1]:     at async /app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36957
2024-10-10T15:20:33.025294958Z app[web.1]:     at async eC.execute (/app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:27552)
2024-10-10T15:20:33.025297763Z app[web.1]:     at async eC.handle (/app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:38291)
2024-10-10T15:20:33.025300378Z app[web.1]:     at async doRender (/app/node_modules/next/dist/server/base-server.js:1345:42)
2024-10-10T15:20:33.025303274Z app[web.1]:     at async cacheEntry.responseCache.get.routeKind (/app/node_modules/next/dist/server/base-server.js:1567:28)
2024-10-10T15:20:33.025305869Z app[web.1]:     at async NextNodeServer.renderToResponseWithComponentsImpl (/app/node_modules/next/dist/server/base-server.js:1475:28)
2024-10-10T15:20:33.025308453Z app[web.1]:     at async NextNodeServer.renderPageComponent (/app/node_modules/next/dist/server/base-server.js:1901:24)
2024-10-10T15:20:33.102723502Z app[web.1]: {"level":"debug","message":"POST request to /api/client_error","timestamp":"2024-10-10 15:20:33"}
2024-10-10T15:20:33.103160857Z app[web.1]: {"level":"error","message":"client side error occured during action 'flightData/fetchQuote'\n======\nError fetching quote data: \n------\n{\"name\":\"Error\",\"message\":\"Error fetching quote data: \",\"stack\":\"Error: Error fetching quote data: \\n    at fetchQuote (https://flightdelay.integration.etherisc.com/_next/static/chunks/app/layout-39dfd358ed90bb54.js:1:15032)\\n    at async https://flightdelay.integration.etherisc.com/_next/static/chunks/app/layout-39dfd358ed90bb54.js:1:15430\\n    at async https://flightdelay.integration.etherisc.com/_next/static/chunks/836-137163563d9c5ff5.js:15:32086\"}\n------\n1728573632986 / 10/10/2024, 3:20:32 PM\n======\n","timestamp":"2024-10-10 15:20:33"}
```

**Comment by doerfli** [comment]
flighstats response
```
{"request":{"airlineCode":{"requestedCode":"BA","fsCode":"BA"},"flightNumber":{"requested":"2231","interpreted":"2231"},"url":"https://api.flightstats.com/flex/ratings/rest/v1/json/flight/BA/2231"},"ratings":[],"appendix":{"airlines":[],"airports":[]}}
```
